name: nesosim3
channels:
  - conda-forge
  - nsidc
  - defaults
dependencies:
  - numpy=1.18.*
  - pyproj=2.6.*
  - python=3.7.*
  - scipy
  - h5py
  - bottleneck
  - dask
  - netcdf4
  - cdsapi
  - xarray
  - cartopy
  - astropy
